version: "3.4"
services:
  plex-server:
    container_name: plex-server
    build: .
    privileged: true
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ} # timezone, defined in .env
    ports:
      - 32400:32400
    volumes:
      - ${DATA}/plex/config/db:/config # plex database
      - ${DATA}/plex/config/transcode:/transcode # temp transcoded files
      - ${DATA}/plex/media:/data # media library